[package]
name = "rustyelf"
version = "0.1.0"
authors = ["Wesley Aptekar-Cassels <W.Aptekar@gmail.com>"]

[dependencies]
byteorder = "1"
clippy = {version = "*", optional = true}

[features]
default = []
